import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Layout } from '../components/layout/Layout';
import { useSEO } from '../hooks/useSEO';
import { FileText, Download, ArrowRight, ShieldCheck, PieChart, Users, CheckCircle2 } from 'lucide-react';
import { NewsletterForm } from '../components/NewsletterForm';
import { useAnalytics } from '../hooks/useAnalytics';

const resources = [
  {
    id: 1,
    title: '2027 Field Service Software Buyer\'s Guide',
    description: 'A comprehensive whitepaper breaking down the ROI of top CRMs by industry size, hidden fee formulas, and feature matrices.',
    type: 'Whitepaper',
    filename: 'fieldappfinder-2027-fsm-buyers-guide.txt',
    icon: <PieChart className="w-8 h-8 text-blue-500" />,
    content: `FIELDAPPFINDER: 2027 FIELD SERVICE SOFTWARE BUYER'S GUIDE
============================================================
Published by FieldAppFinder Editorial Team
Focus: ROI Benchmarks, Contract Traps & Software Selection Matrix

1. EXECUTIVE EVALUATION FRAMEWORK
- Crew 1-3 Techs: Prioritize zero-setup-fee, fast month-to-month solutions (e.g., Jobber, Housecall Pro, ServiceM8).
- Crew 4-10 Techs: Prioritize flat team rates, automated route density, and QuickBooks/Xero 2-way sync (e.g., ServiceM8).
- Call & Lead Capture: Eliminate missed after-hours emergency calls 24/7 with automated AI voice dispatch (e.g., LucroVox).

2. 5 QUESTIONS TO ASK BEFORE SIGNING ANY SAAS CONTRACT
1. What is the merchant credit card processing markup rate? (Target: <= 2.7% + 30¢ for card-present).
2. Is there a surcharge penalty for using an external merchant gateway?
3. What is the cancellation window? (Watch out for strict 60-day auto-renewals).
4. How many SMS texts and voice call minutes are included before per-message overage billing?
5. Does the technician mobile app work 100% offline in basements, crawlspaces, and rural dead zones?

3. CORE FEATURE ESSENTIALS CHECKLIST
[ ] Mobile Invoicing & Digital Signature Capture
[ ] Real-time GPS Breadcrumb Dispatching
[ ] 2-way Real-time Accounting Sync (QuickBooks Online / Desktop)
[ ] Multi-tier "Good / Better / Best" Estimating
[ ] Customer Self-Service Client Hub & Online Booking

Generated by FieldAppFinder.com - Field-Tested Software Reviews`
  },
  {
    id: 2,
    title: 'Contractor Tax Compliance Checklist',
    description: 'Ensure your business is protected with this practical checklist covering 1099/W2 rules, sales tax nexus, and digital audit readiness.',
    type: 'Checklist',
    filename: 'contractor-tax-compliance-checklist.txt',
    icon: <ShieldCheck className="w-8 h-8 text-emerald-500" />,
    content: `CONTRACTOR TAX & FINANCIAL COMPLIANCE CHECKLIST (2026-2027)
============================================================
FieldAppFinder Operational Compliance Series

SECTION 1: SUB-CONTRACTOR (1099-NEC) vs. EMPLOYEE (W-2)
[ ] Form W-9 collected from EVERY subcontractor BEFORE issuing first payment.
[ ] Subcontractor General Liability & Workers' Comp COI verified current on file.
[ ] Written Independent Contractor Agreement signed outlining project milestones.

SECTION 2: MULTI-JURISDICTION SALES TAX RULES
[ ] Labor vs. Materials split verified according to state rules (capital improvement exemptions).
[ ] County, city, and special district sales tax rates automated via CRM/accounting sync.
[ ] Resale exemption certificates stored on file for wholesale material purchases.

SECTION 3: DIGITAL RECORD RETENTION
[ ] Digital photo documentation attached to every completed job ticket.
[ ] Fuel and supply receipts digitally categorized with GPS timestamps.
[ ] Vehicle mileage logs maintained via automated GPS fleet software.

Generated by FieldAppFinder.com - Independent Contractor Software Reviews`
  },
  {
    id: 3,
    title: 'How to Train Techs on New Software',
    description: 'A step-by-step 14-day guide to onboarding field technicians without disrupting your daily dispatch schedule.',
    type: 'Guide',
    filename: '14-day-tech-software-training-playbook.txt',
    icon: <Users className="w-8 h-8 text-amber-500" />,
    content: `14-DAY FIELD TECHNICIAN SOFTWARE ROLLOUT PLAYBOOK
===================================================
How to Overcome Crew Pushback and Achieve 100% Adoption

PHASE 1: DAYS 1-3 (LEAD TECH BUY-IN)
- Appoint your most respected field technician as "Tech Ambassador".
- Have the ambassador run test jobs and provide input before rolling out to everyone.
- Frame the software as: "This gets you home 45 minutes earlier by eliminating paper tickets."

PHASE 2: DAYS 4-7 (CONTROLLED PILOT)
- Run software alongside paper tickets for exactly 3 days on 2 trucks only.
- Focus exclusively on 3 actions: Clocking In, Clocking Out, and Uploading Job Photos.
- Keep billing and credit card processing on existing systems during this week.

PHASE 3: DAYS 8-14 (FULL FLEET LAUNCH)
- 30-minute breakfast training session with real mobile devices.
- Incentivize accuracy: award a $100 gift card to the first tech with 100% complete digital tickets.
- Cease printing paper work orders completely on Day 14.

Generated by FieldAppFinder.com - Practical Trade Growth Systems`
  },
  {
    id: 4,
    title: 'Estimating & Quoting Templates',
    description: 'Free, customizable Good-Better-Best quotation templates designed to increase job ticket size and customer closing rates.',
    type: 'Template',
    filename: 'good-better-best-quoting-templates.txt',
    icon: <FileText className="w-8 h-8 text-purple-500" />,
    content: `GOOD / BETTER / BEST CONTRACTOR ESTIMATE TEMPLATE
==================================================
Formula for 20%+ Higher Average Job Ticket Size

OPTION 1: THE ECONOMY REPAIR (GOOD)
- Description: Solves immediate critical malfunction to restore system operation.
- Scope: 
  * Replace failed component / valve / motor.
  * Standard safety inspection.
  * 30-day labor warranty.
- Target Pricing: Base labor + standard retail parts markup.

OPTION 2: THE RECOMMENDED SOLUTION (BETTER) - ★ HIGHEST VALUE
- Description: Repairs immediate problem and replaces high-wear adjacent components to prevent recurring breakdown.
- Scope:
  * Complete repair package + secondary wear components.
  * Comprehensive 21-point system tune-up and cleaning.
  * 1-Year parts & labor guarantee.
  * 1-Year complimentary seasonal maintenance visit.
- Target Pricing: Option 1 price + 35% margin.

OPTION 3: PREMIUM SYSTEM RESTORATION (BEST)
- Description: Complete operational overhaul ensuring maximum energy efficiency and longest service life.
- Scope:
  * Complete heavy-duty replacement package.
  * Surge protection / filtration upgrade.
  * 3-Year comprehensive replacement warranty.
  * VIP priority dispatch service.
- Target Pricing: Option 1 price + 75% margin.

ESSENTIAL PROPOSAL TERMS & CONDITIONS:
1. Valid for 30 calendar days from presentation.
2. Unforeseen structural or concealed piping rot billed at standard time & materials rate upon written homeowner change-order.
3. 50% deposit required upon authorization; remainder due upon practical completion.

Generated by FieldAppFinder.com`
  }
];

export function Resources() {
  useSEO('Resource Center for Home Service Pros', 'Free white papers, compliance checklists, and guides for growing your home service business.');
  const { trackEvent } = useAnalytics();
  const [downloadedId, setDownloadedId] = useState<number | null>(null);

  const handleDownload = (resource: typeof resources[0]) => {
    trackEvent('resource_download', { resource_id: resource.id, resource_title: resource.title });

    const blob = new Blob([resource.content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = resource.filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloadedId(resource.id);
    setTimeout(() => setDownloadedId(null), 3500);
  };

  return (
    <Layout>
      <div className="bg-slate-50 dark:bg-slate-900 py-16 border-b border-slate-200 dark:border-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl">
            <h1 className="text-4xl font-bold text-slate-900 dark:text-white mb-6">Resource Center</h1>
            <p className="text-lg text-slate-600 dark:text-slate-300">
              Free guides, checklists, and templates to help you run a more profitable and compliant home service business.
            </p>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        {/* Featured Interactive Calculator Banner */}
        <div className="mb-12 bg-gradient-to-r from-blue-900 via-indigo-900 to-slate-900 rounded-2xl p-6 sm:p-10 text-white shadow-lg border border-blue-800/50 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
          <div className="max-w-2xl">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-blue-500/30 text-blue-200 border border-blue-400/30 mb-3">
              ⚡ High-Impact Free Tool
            </span>
            <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              Interactive Contractor Software ROI & Time-Savings Calculator
            </h2>
            <p className="text-blue-100 text-sm sm:text-base mt-2">
              Input your crew size, hourly rate, and weekly paperwork to calculate exact monthly labor savings, recovered lost phone leads, and net profit gains.
            </p>
          </div>
          <Link
            to="/calculator"
            className="inline-flex items-center justify-center px-6 py-3.5 rounded-xl bg-blue-500 hover:bg-blue-400 text-white text-base font-bold shadow-md transition-all hover:scale-105 flex-shrink-0 cursor-pointer"
          >
            Launch Calculator
            <ArrowRight className="w-5 h-5 ml-2" />
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-8">
          {resources.map((resource) => (
            <div key={resource.id} className="bg-white dark:bg-slate-900 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 p-8 flex flex-col sm:flex-row gap-6 items-start hover:shadow-md transition-shadow">
              <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-lg flex-shrink-0">
                {resource.icon}
              </div>
              <div className="flex-1">
                <div className="text-sm font-semibold text-slate-600 dark:text-slate-300 uppercase tracking-wider mb-2">
                  {resource.type}
                </div>
                <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">{resource.title}</h3>
                <p className="text-slate-600 dark:text-slate-300 mb-6">{resource.description}</p>
                <button 
                  onClick={() => handleDownload(resource)}
                  aria-label={`Download ${resource.title}`}
                  className={`flex items-center gap-2 font-medium px-4 py-2 rounded-lg transition-all cursor-pointer text-sm ${
                    downloadedId === resource.id
                      ? 'bg-emerald-100 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 font-semibold'
                      : 'text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 bg-blue-50 dark:bg-blue-900/30 hover:bg-blue-100 dark:hover:bg-blue-900/50'
                  }`}
                >
                  {downloadedId === resource.id ? (
                    <>
                      <CheckCircle2 className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                      Downloaded!
                    </>
                  ) : (
                    <>
                      <Download className="w-4 h-4" />
                      Download Now
                    </>
                  )}
                </button>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-20 bg-blue-600 rounded-2xl p-8 sm:p-12 text-center text-white shadow-xl relative overflow-hidden">
          <div className="relative z-10 max-w-2xl mx-auto">
            <h2 className="text-3xl font-bold mb-4">Want more resources like this?</h2>
            <p className="text-blue-100 mb-8 text-lg">
              Join our newsletter to get the latest guides, templates, and software reviews sent directly to your inbox.
            </p>
            <div className="bg-white/10 p-6 rounded-xl backdrop-blur-sm border border-white/20">
               <NewsletterForm />
            </div>
          </div>
          {/* Decorative background elements */}
          <div className="absolute top-0 right-0 -mt-20 -mr-20 w-80 h-80 bg-blue-500 rounded-full blur-3xl opacity-50 z-0"></div>
          <div className="absolute bottom-0 left-0 -mb-20 -ml-20 w-80 h-80 bg-blue-700 rounded-full blur-3xl opacity-50 z-0"></div>
        </div>
      </div>
    </Layout>
  );
}
