import React, { useState } from 'react';
import { Target, CheckCircle2, ArrowRight, Download, FileText, Sparkles } from 'lucide-react';
import { useAnalytics } from '../hooks/useAnalytics';
import { db } from '../lib/firebase';
import { collection, addDoc, doc, setDoc, increment, serverTimestamp } from 'firebase/firestore';

export function LeadMagnetWidget() {
  const { trackEvent } = useAnalytics();
  const [step, setStep] = useState(1);
  const [trade, setTrade] = useState('');
  const [size, setSize] = useState('');
  const [email, setEmail] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const [recommendedTool, setRecommendedTool] = useState('Jobber');

  const getRecommendation = (selectedTrade: string, teamSize: string) => {
    if (teamSize.includes('11-25') || teamSize.includes('25+')) {
      return selectedTrade === 'Plumbing' || selectedTrade === 'HVAC' ? 'ServiceM8' : 'Housecall Pro';
    }
    if (selectedTrade === 'Landscaping' || selectedTrade === 'Cleaning') {
      return 'Jobber';
    }
    return 'Jobber';
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const recommendation = getRecommendation(trade, size);
    setRecommendedTool(recommendation);
    setSubmitted(true);

    trackEvent('lead_captured', {
      trade,
      team_size: size,
      email,
      recommended: recommendation
    });

    try {
      // Save lead to Firestore database
      await addDoc(collection(db, 'quiz_leads'), {
        industry: trade || 'Contracting',
        size: size || '1-3',
        goal: 'Software Matchmaker Recommendation',
        email: email.trim().toLowerCase(),
        recommendedProduct: recommendation,
        createdAt: serverTimestamp()
      });

      // Increment total leads counter
      const totalsRef = doc(db, 'analytics', 'totals');
      await setDoc(totalsRef, { totalLeads: increment(1) }, { merge: true });
    } catch (err) {
      console.warn('Could not record lead to database (offline or permission limit):', err);
    }
  };

  const handleDownloadReport = () => {
    trackEvent('lead_report_downloaded', { trade, recommended: recommendedTool });
    const content = `CONTRACTOR SOFTWARE STACK EVALUATION MATRIX
Industry: ${trade}
Crew Size: ${size}
Primary Recommendation: ${recommendedTool}
Date: ${new Date().toLocaleDateString()}

TOP 3 RECOMMENDED TOOLS FOR ${trade.toUpperCase()}:
1. ${recommendedTool} - Best overall operational match for ${size} technicians.
2. Housecall Pro - Strong mobile dispatch, quick customer booking.
3. Jobber - Exceptional quoting workflows and client self-serve hub.

ESSENTIAL EVALUATION CHECKLIST:
[ ] 2-way QuickBooks / Xero live sync
[ ] Mobile GPS routing and real-time technician dispatch
[ ] Automated customer SMS reminders (on-my-way messages)
[ ] In-field credit card processing fee transparency (< 2.9% + 30c)
[ ] Tiered service agreement / maintenance plan recurring billing

Generated by FieldAppFinder (fieldappfinder.com).`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${trade.toLowerCase() || 'contractor'}-software-recommendations.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (submitted) {
    return (
      <div className="bg-gradient-to-br from-blue-900 to-indigo-900 rounded-2xl p-8 sm:p-10 my-12 text-center text-white shadow-xl">
        <div className="w-16 h-16 bg-emerald-500/20 rounded-full flex items-center justify-center mx-auto mb-6">
          <CheckCircle2 className="w-8 h-8 text-emerald-400" />
        </div>
        <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-blue-500/30 border border-blue-400/30 rounded-full text-xs font-semibold text-blue-200 mb-3">
          <Sparkles className="w-3.5 h-3.5 text-blue-300" /> Matched for {trade} ({size})
        </div>
        <h3 className="text-2xl font-bold mb-2">Your Recommendation: {recommendedTool}</h3>
        <p className="text-blue-200 max-w-lg mx-auto mb-6 text-sm">
          We've logged your request for ({email}). You can also download your immediate customized software scorecard and negotiation checklist right now below.
        </p>

        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 max-w-md mx-auto">
          <button
            onClick={handleDownloadReport}
            className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-6 py-3 bg-yellow-400 hover:bg-yellow-300 text-slate-900 font-bold rounded-xl transition-colors shadow-lg cursor-pointer text-sm"
          >
            <Download className="w-4 h-4" /> Download Custom Report Now
          </button>
          <a
            href={`/go/${recommendedTool.toLowerCase().replace(/\s+/g, '')}`}
            target="_blank"
            rel="sponsored noopener noreferrer"
            className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-6 py-3 bg-white/10 hover:bg-white/20 text-white font-semibold rounded-xl border border-white/20 transition-colors text-sm"
          >
            Explore {recommendedTool} <ArrowRight className="w-4 h-4" />
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl overflow-hidden shadow-2xl my-12 border border-slate-700 flex flex-col md:flex-row">
      <div className="p-8 md:p-10 md:w-5/12 flex flex-col justify-center border-b md:border-b-0 md:border-r border-slate-700/50 relative">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,_var(--tw-gradient-stops))] from-blue-500/10 via-transparent to-transparent pointer-events-none" />
        <div className="bg-blue-500/20 text-blue-400 w-12 h-12 rounded-xl flex items-center justify-center mb-6">
          <Target className="w-6 h-6" />
        </div>
        <h3 className="text-2xl font-bold text-white mb-3">Software Matchmaker</h3>
        <p className="text-slate-400 text-sm leading-relaxed mb-6">
          Overwhelmed by choices? Tell us a bit about your business, and our algorithm will calculate the perfect software stack for your needs.
        </p>
        <div className="flex items-center gap-2 text-xs font-bold text-slate-500 uppercase tracking-wider">
          <span className={`w-2 h-2 rounded-full ${step >= 1 ? 'bg-blue-500' : 'bg-slate-700'}`} />
          <span className={`w-2 h-2 rounded-full ${step >= 2 ? 'bg-blue-500' : 'bg-slate-700'}`} />
          <span className={`w-2 h-2 rounded-full ${step >= 3 ? 'bg-blue-500' : 'bg-slate-700'}`} />
        </div>
      </div>
      
      <div className="p-8 md:p-10 md:w-7/12 bg-slate-800/50 flex flex-col justify-center">
        {step === 1 && (
          <div className="animate-in fade-in slide-in-from-right-4 duration-300">
            <h4 className="text-lg font-semibold text-white mb-4">1. What's your primary trade?</h4>
            <div className="grid grid-cols-2 gap-3">
              {['HVAC', 'Plumbing', 'Electrical', 'Landscaping', 'Cleaning', 'General Contracting'].map(t => (
                <button 
                  key={t}
                  onClick={() => { 
                    setTrade(t); 
                    setStep(2); 
                    trackEvent('lead_magnet_step', { step: 2, trade: t });
                  }}
                  className="px-4 py-3 bg-slate-700/50 hover:bg-blue-600 border border-slate-600 hover:border-blue-500 rounded-lg text-slate-200 text-sm font-medium transition-all text-left"
                >
                  {t}
                </button>
              ))}
            </div>
          </div>
        )}

        {step === 2 && (
          <div className="animate-in fade-in slide-in-from-right-4 duration-300">
            <h4 className="text-lg font-semibold text-white mb-4">2. How many field techs do you have?</h4>
            <div className="flex flex-col gap-3">
              {['1-3 (Just starting out)', '4-10 (Growing team)', '11-25 (Mid-size operation)', '25+ (Enterprise)'].map(s => (
                <button 
                  key={s}
                  onClick={() => { 
                    setSize(s); 
                    setStep(3); 
                    trackEvent('lead_magnet_step', { step: 3, trade, team_size: s });
                  }}
                  className="px-4 py-3 bg-slate-700/50 hover:bg-blue-600 border border-slate-600 hover:border-blue-500 rounded-lg text-slate-200 text-sm font-medium transition-all text-left flex justify-between items-center group"
                >
                  {s} <ArrowRight className="w-4 h-4 opacity-0 group-hover:opacity-100 transition-opacity" />
                </button>
              ))}
            </div>
            <button onClick={() => setStep(1)} className="text-slate-300 text-sm mt-4 hover:text-white transition-colors">&larr; Back</button>
          </div>
        )}

        {step === 3 && (
          <div className="animate-in fade-in slide-in-from-right-4 duration-300">
            <h4 className="text-lg font-semibold text-white mb-2">3. Where should we send your results?</h4>
            <p className="text-slate-300 text-sm mb-6">We'll email you the top 3 recommended platforms for a {trade} business with {size} techs, plus exclusive affiliate discount links.</p>
            <form onSubmit={handleSubmit} className="flex flex-col gap-4">
              <label htmlFor="lead-magnet-work-email" className="sr-only">Work email address</label>
              <input 
                id="lead-magnet-work-email"
                type="email" 
                aria-label="Work email address"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="Enter your work email..." 
                className="w-full px-4 py-3 bg-slate-900 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              <button 
                type="submit"
                className="w-full py-3 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-lg transition-colors flex items-center justify-center gap-2 cursor-pointer"
              >
                Get My Recommendations <ArrowRight className="w-4 h-4" />
              </button>
            </form>
            <button onClick={() => setStep(2)} className="text-slate-300 text-sm mt-4 hover:text-white transition-colors">&larr; Back</button>
          </div>
        )}
      </div>
    </div>
  );
}
